//! `gitvault init` onboarding command (REQ-71).
//!
//! 4-step idempotent orchestrator:
//!   1. Identity — ensure an identity key exists
//!   2. Recipients — add self as a recipient
//!   3. Harden — install git hooks and .gitignore entries
//!   4. Config — create a minimal `.gitvault/config.toml` if absent

use crate::cli::IdentityProfile;
use crate::commands::CommandOutcome;
use crate::error::GitvaultError;
use crate::identity::{IdentitySourceState, probe_identity_sources};

/// Minimal config template written by `gitvault init`.
const CONFIG_TEMPLATE: &str = r#"# gitvault configuration — generated by gitvault init
# See: https://github.com/your-org/gitvault#configuration

[paths]
# recipients_dir = ".secrets/recipients"  # default

[barrier]
# prod_name = "prod"  # environment name that requires production barrier
"#;

/// Run the `gitvault init` onboarding command (REQ-71).
///
/// Executes four idempotent steps:
///   1. Identity setup
///   2. Self-as-recipient registration
///   3. Repository hardening
///   4. Config file creation
///
/// # Errors
///
/// Returns [`GitvaultError`] if the command is not run inside a git repository,
/// or if any non-idempotent step fails.
pub fn cmd_init(
    env_name: Option<String>,
    out: Option<String>,
    json: bool,
    no_prompt: bool,
) -> Result<CommandOutcome, GitvaultError> {
    // Must be run inside a git repo.
    let repo_root = crate::repo::find_repo_root()?;

    // Accumulate step results for JSON output.
    let mut step_results: Vec<serde_json::Value> = Vec::new();

    // ── Step 1: Identity ────────────────────────────────────────────────────
    let sources = probe_identity_sources(None, None);
    let identity_resolved = sources
        .iter()
        .any(|s| matches!(s, IdentitySourceState::Resolved { .. }));

    if identity_resolved {
        let source_name = sources
            .iter()
            .find_map(|s| {
                if let IdentitySourceState::Resolved { source } = s {
                    Some(source.as_str())
                } else {
                    None
                }
            })
            .unwrap_or("unknown");

        if json {
            step_results.push(serde_json::json!({
                "step": "identity",
                "status": "skipped",
                "reason": format!("already set up: {source_name}")
            }));
        } else {
            println!("✓ Identity already set up: {source_name}");
        }
    } else {
        crate::commands::identity::cmd_identity_create(
            IdentityProfile::Classic,
            out,
            json,
            no_prompt,
        )?;
        if json {
            step_results.push(serde_json::json!({
                "step": "identity",
                "status": "created"
            }));
        } else {
            println!("✓ Identity ready");
        }
    }

    // ── Step 2: Recipients ──────────────────────────────────────────────────
    match crate::commands::recipients::cmd_recipient_add_self(None, false) {
        Ok(_) => {
            if json {
                step_results.push(serde_json::json!({
                    "step": "recipients",
                    "status": "added"
                }));
            } else {
                println!("✓ Added self as recipient");
                println!("  → git add .secrets/recipients/ && git commit");
            }
        }
        Err(GitvaultError::Usage(ref msg)) if msg.to_lowercase().contains("already") => {
            if json {
                step_results.push(serde_json::json!({
                    "step": "recipients",
                    "status": "skipped",
                    "reason": "already a recipient"
                }));
            } else {
                println!("✓ Already a recipient");
                println!("  → git add .secrets/recipients/ && git commit");
            }
        }
        Err(e) => return Err(e),
    }

    // ── Step 3: Harden ──────────────────────────────────────────────────────
    crate::commands::admin::cmd_harden(json, no_prompt)?;
    if json {
        step_results.push(serde_json::json!({
            "step": "harden",
            "status": "done"
        }));
    } else {
        println!("✓ Repository hardened");
    }

    // ── Step 4: Config ──────────────────────────────────────────────────────
    let config_dir = repo_root.join(".gitvault");
    let config_path = config_dir.join("config.toml");

    if config_path.exists() {
        if json {
            step_results.push(serde_json::json!({
                "step": "config",
                "status": "skipped",
                "reason": "already exists"
            }));
        } else {
            println!("✓ Config already exists");
        }
    } else {
        std::fs::create_dir_all(&config_dir).map_err(|e| {
            GitvaultError::Other(format!("failed to create .gitvault/ directory: {e}"))
        })?;
        std::fs::write(&config_path, CONFIG_TEMPLATE).map_err(|e| {
            GitvaultError::Other(format!("failed to write .gitvault/config.toml: {e}"))
        })?;
        if json {
            step_results.push(serde_json::json!({
                "step": "config",
                "status": "created",
                "path": ".gitvault/config.toml"
            }));
        }
    }
    if !json {
        println!("✓ Config ready");
    }

    // ── --env handling ───────────────────────────────────────────────────────
    if let Some(ref env) = env_name {
        let secrets_dir = repo_root.join(".secrets");
        std::fs::create_dir_all(&secrets_dir).map_err(|e| {
            GitvaultError::Other(format!("failed to create .secrets/ directory: {e}"))
        })?;
        std::fs::write(secrets_dir.join("env"), env)
            .map_err(|e| GitvaultError::Other(format!("failed to write .secrets/env: {e}")))?;
        if json {
            step_results.push(serde_json::json!({
                "step": "env",
                "status": "written",
                "env": env
            }));
        } else {
            println!("✓ Environment set to: {env}");
        }
    }

    // ── Final output ─────────────────────────────────────────────────────────
    if json {
        println!(
            "{}",
            serde_json::to_string_pretty(&step_results).unwrap_or_default()
        );
    } else {
        // Derive a display name for the commit message hint.
        let git_name = std::process::Command::new("git")
            .args(["config", "user.name"])
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "you".to_string());

        println!();
        println!("gitvault init complete!");
        println!("Next steps:");
        println!(
            "  1. git add .secrets/recipients/ && git commit -m \"onboard: add {git_name} as recipient\""
        );
        println!("  2. Ask a maintainer who can decrypt all secrets to run: gitvault rekey");
        println!("  3. After they push, run: git pull && gitvault decrypt <file>");
    }

    Ok(CommandOutcome::Success)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::test_helpers::{
        CwdGuard, global_test_lock, init_git_repo, setup_identity_file, with_identity_env,
    };
    use tempfile::TempDir;

    /// Helper: set up a temp dir with a git repo and identity env variable.
    fn setup_test_repo() -> (TempDir, tempfile::NamedTempFile, age::x25519::Identity) {
        let dir = TempDir::new().expect("temp dir should be created");
        init_git_repo(dir.path());
        // Configure git user so recipients filename derivation works.
        std::process::Command::new("git")
            .args(["config", "user.name", "Test User"])
            .current_dir(dir.path())
            .status()
            .expect("git config user.name should succeed");
        std::process::Command::new("git")
            .args(["config", "user.email", "test@example.com"])
            .current_dir(dir.path())
            .status()
            .expect("git config user.email should succeed");
        let (identity_file, identity) = setup_identity_file();
        (dir, identity_file, identity)
    }

    #[test]
    fn test_init_creates_config() {
        let _lock = global_test_lock().lock().unwrap();
        let (dir, identity_file, _identity) = setup_test_repo();
        let _cwd = CwdGuard::enter(dir.path());

        with_identity_env(identity_file.path(), || {
            let result = cmd_init(None, None, false, true);
            assert!(result.is_ok(), "cmd_init should succeed: {result:?}");
        });

        let config_path = dir.path().join(".gitvault/config.toml");
        assert!(
            config_path.exists(),
            ".gitvault/config.toml should be created"
        );
        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(
            content.contains("[paths]"),
            "config should contain [paths] section"
        );
        assert!(
            content.contains("[barrier]"),
            "config should contain [barrier] section"
        );
    }

    #[test]
    fn test_init_idempotent() {
        let _lock = global_test_lock().lock().unwrap();
        let (dir, identity_file, _identity) = setup_test_repo();
        let _cwd = CwdGuard::enter(dir.path());

        with_identity_env(identity_file.path(), || {
            let first = cmd_init(None, None, false, true);
            assert!(first.is_ok(), "first cmd_init should succeed: {first:?}");

            let second = cmd_init(None, None, false, true);
            assert!(
                second.is_ok(),
                "second cmd_init should succeed (idempotent): {second:?}"
            );
        });
    }

    #[test]
    fn test_init_env_writes_env_file() {
        let _lock = global_test_lock().lock().unwrap();
        let (dir, identity_file, _identity) = setup_test_repo();
        let _cwd = CwdGuard::enter(dir.path());

        with_identity_env(identity_file.path(), || {
            let result = cmd_init(Some("staging".to_string()), None, false, true);
            assert!(
                result.is_ok(),
                "cmd_init with --env should succeed: {result:?}"
            );
        });

        let env_file = dir.path().join(".secrets/env");
        assert!(env_file.exists(), ".secrets/env should be created");
        let content = std::fs::read_to_string(&env_file).unwrap();
        assert_eq!(
            content.trim(),
            "staging",
            ".secrets/env should contain 'staging'"
        );
    }
}
