//! AWS SSM Parameter Store backend (REQ-26 to REQ-30, REQ-49).
//!
//! All functions in this module are gated behind the `ssm` Cargo feature.
//!
//! # Architecture
//!
//! The [`SsmBackend`] trait abstracts the two SSM operations used by all
//! commands (fetch parameters, put a parameter).  [`RealSsmBackend`] wraps the
//! real `aws_sdk_ssm::Client`; tests inject [`MockSsmBackend`] — an in-memory
//! store — so every command path can be covered without live AWS credentials.
//!
//! Public commands (`cmd_ssm_*`) build a [`RealSsmBackend`] and delegate to
//! the corresponding `*_with` function, keeping all logic testable.

mod backend;
mod commands;
mod refs;

pub use backend::{RealSsmBackend, SsmBackend};
pub use commands::{cmd_ssm_diff, cmd_ssm_pull, cmd_ssm_push, cmd_ssm_set};
pub use refs::{refs_file_path, ssm_path};

#[cfg(test)]
mod tests {
    use super::backend::MockSsmBackend;
    use super::commands::{
        cmd_ssm_diff, cmd_ssm_diff_with, cmd_ssm_pull, cmd_ssm_pull_with, cmd_ssm_push,
        cmd_ssm_push_with, cmd_ssm_set, cmd_ssm_set_with,
    };
    use super::refs::{
        get_app_name, load_refs, refs_file_path, save_refs, ssm_path, validate_app_name,
    };
    use crate::aws_config::AwsConfig;
    use crate::error::GitvaultError;
    use std::collections::HashMap;
    use tempfile::TempDir;

    // `MockSsmBackend` is auto-generated by mockall from the
    // `#[cfg_attr(test, mockall::automock)]` attribute on `SsmBackend`.

    // ── Pure helper tests (sync) ──────────────────────────────────────────────

    #[test]
    fn test_ssm_path_format() {
        assert_eq!(ssm_path("myapp", "prod", "DB_PASS"), "/myapp/prod/DB_PASS");
        assert_eq!(ssm_path("app", "dev", "KEY"), "/app/dev/KEY");
    }

    #[test]
    fn test_refs_file_path() {
        let dir = TempDir::new().unwrap();
        let expected = dir
            .path()
            .join("secrets")
            .join("prod")
            .join(".ssm-refs.json");
        assert_eq!(refs_file_path(dir.path(), "prod"), expected);
    }

    #[tokio::test]
    async fn test_serde_refs() {
        let dir = TempDir::new().unwrap();
        let mut refs: HashMap<String, String> = HashMap::new();
        refs.insert("DB_PASS".to_string(), "/myapp/staging/DB_PASS".to_string());
        refs.insert("API_KEY".to_string(), "/myapp/staging/API_KEY".to_string());
        save_refs(dir.path(), "staging", &refs)
            .await
            .expect("save_refs should succeed");
        let loaded = load_refs(dir.path(), "staging")
            .await
            .expect("load_refs should succeed");
        assert_eq!(
            loaded.get("DB_PASS").map(String::as_str),
            Some("/myapp/staging/DB_PASS")
        );
        assert_eq!(
            loaded.get("API_KEY").map(String::as_str),
            Some("/myapp/staging/API_KEY")
        );
        assert_eq!(loaded.len(), 2);
    }

    #[tokio::test]
    async fn test_load_refs_missing_file_returns_empty() {
        let dir = TempDir::new().unwrap();
        let refs = load_refs(dir.path(), "dev")
            .await
            .expect("should return empty map");
        assert!(refs.is_empty());
    }

    #[test]
    fn test_validate_app_name_accepts_valid() {
        assert!(validate_app_name("myapp").is_ok());
        assert!(validate_app_name("my-app_v2.0").is_ok());
        assert!(validate_app_name("gitvault").is_ok());
    }

    #[test]
    fn test_validate_app_name_rejects_invalid() {
        assert!(validate_app_name("my app").is_err());
        assert!(validate_app_name("app/name").is_err());
        assert!(validate_app_name("app@name").is_err());
    }

    // ── get_app_name ──────────────────────────────────────────────────────────

    #[tokio::test]
    async fn test_get_app_name_from_git_remote() {
        let dir = TempDir::new().unwrap();
        std::process::Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .status()
            .unwrap();
        std::process::Command::new("git")
            .args([
                "remote",
                "add",
                "origin",
                "https://github.com/user/myrepo.git",
            ])
            .current_dir(dir.path())
            .status()
            .unwrap();
        let name = get_app_name(dir.path())
            .await
            .expect("should extract name from remote");
        assert_eq!(name, "myrepo");
    }

    #[tokio::test]
    async fn test_get_app_name_fallback_to_dir_name() {
        let dir = TempDir::new().unwrap();
        // No git repo → git command fails → falls back to directory name.
        // temp-dir names are alphanumeric so validate_app_name succeeds.
        let result = get_app_name(dir.path()).await;
        assert!(
            result.is_ok() || matches!(result, Err(GitvaultError::Usage(_))),
            "unexpected error: {result:?}"
        );
    }

    // ── cmd_ssm_pull_with ─────────────────────────────────────────────────────

    #[tokio::test]
    async fn test_cmd_ssm_pull_with_writes_refs() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params().times(1).returning(|_| {
            Ok(vec![
                ("/myapp/dev/DB_PASS".to_string(), "secret1".to_string()),
                ("/myapp/dev/API_KEY".to_string(), "secret2".to_string()),
            ])
        });

        cmd_ssm_pull_with(dir.path(), "dev", &mock, "myapp", false)
            .await
            .expect("pull should succeed");

        let refs = load_refs(dir.path(), "dev").await.unwrap();
        assert_eq!(
            refs.get("DB_PASS").map(String::as_str),
            Some("/myapp/dev/DB_PASS")
        );
        assert_eq!(
            refs.get("API_KEY").map(String::as_str),
            Some("/myapp/dev/API_KEY")
        );
        assert_eq!(refs.len(), 2);
    }

    #[tokio::test]
    async fn test_cmd_ssm_pull_with_empty_ssm_writes_empty_refs() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params()
            .times(1)
            .returning(|_| Ok(vec![]));

        cmd_ssm_pull_with(dir.path(), "dev", &mock, "myapp", false)
            .await
            .expect("pull should succeed with empty SSM");

        let refs = load_refs(dir.path(), "dev").await.unwrap();
        assert!(refs.is_empty());
    }

    #[tokio::test]
    async fn test_cmd_ssm_pull_with_json_output() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params()
            .times(1)
            .returning(|_| Ok(vec![("/myapp/dev/KEY".to_string(), "val".to_string())]));

        cmd_ssm_pull_with(dir.path(), "dev", &mock, "myapp", true)
            .await
            .expect("pull --json should succeed");
    }

    // ── cmd_ssm_diff_with ─────────────────────────────────────────────────────

    #[tokio::test]
    async fn test_cmd_ssm_diff_with_in_sync() {
        let dir = TempDir::new().unwrap();
        let mut refs = HashMap::new();
        refs.insert("DB_PASS".to_string(), "/myapp/dev/DB_PASS".to_string());
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params().times(1).returning(|_| {
            Ok(vec![(
                "/myapp/dev/DB_PASS".to_string(),
                "secret".to_string(),
            )])
        });

        cmd_ssm_diff_with(dir.path(), "dev", &mock, "myapp", false, false)
            .await
            .expect("diff should succeed");
    }

    #[tokio::test]
    async fn test_cmd_ssm_diff_with_only_local() {
        let dir = TempDir::new().unwrap();
        let mut refs = HashMap::new();
        refs.insert(
            "MISSING_KEY".to_string(),
            "/myapp/dev/MISSING_KEY".to_string(),
        );
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params()
            .times(1)
            .returning(|_| Ok(vec![]));

        cmd_ssm_diff_with(dir.path(), "dev", &mock, "myapp", false, false)
            .await
            .expect("diff should succeed when key only in local");
    }

    #[tokio::test]
    async fn test_cmd_ssm_diff_with_only_ssm() {
        let dir = TempDir::new().unwrap();
        // No local refs — SSM has a new key.
        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params()
            .times(1)
            .returning(|_| Ok(vec![("/myapp/dev/NEW_KEY".to_string(), "v".to_string())]));

        cmd_ssm_diff_with(dir.path(), "dev", &mock, "myapp", true, false)
            .await
            .expect("diff should succeed when key only in SSM");
    }

    /// JSON diff: exercises the `only_local` and `in_sync` branches in json mode.
    #[tokio::test]
    async fn test_cmd_ssm_diff_with_json_all_branches() {
        let dir = TempDir::new().unwrap();
        // Local has LOCAL_ONLY and IN_SYNC; SSM has IN_SYNC and SSM_ONLY.
        let mut refs = HashMap::new();
        refs.insert(
            "LOCAL_ONLY".to_string(),
            "/myapp/dev/LOCAL_ONLY".to_string(),
        );
        refs.insert("IN_SYNC".to_string(), "/myapp/dev/IN_SYNC".to_string());
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params().times(1).returning(|_| {
            Ok(vec![
                ("/myapp/dev/IN_SYNC".to_string(), "v1".to_string()),
                ("/myapp/dev/SSM_ONLY".to_string(), "v2".to_string()),
            ])
        });

        cmd_ssm_diff_with(dir.path(), "dev", &mock, "myapp", false, true)
            .await
            .expect("diff --json should cover all match arms");
    }

    #[tokio::test]
    async fn test_cmd_ssm_diff_with_reveal_flag() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_fetch_params().times(1).returning(|_| {
            Ok(vec![(
                "/myapp/dev/SECRET".to_string(),
                "plaintext".to_string(),
            )])
        });

        // reveal=true exposes actual values in the non-json diff output
        cmd_ssm_diff_with(dir.path(), "dev", &mock, "myapp", true, false)
            .await
            .expect("diff --reveal should succeed");
    }

    // ── cmd_ssm_set_with ──────────────────────────────────────────────────────

    /// Verifies the exact SSM path and value passed to `put_param`, and that
    /// the local refs file is updated.
    #[tokio::test]
    async fn test_cmd_ssm_set_with_calls_put_with_correct_args() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_put_param()
            .withf(|path, value| path == "/myapp/dev/DB_PASS" && value == "secret123")
            .times(1)
            .returning(|_, _| Ok(()));

        cmd_ssm_set_with(
            dir.path(),
            "dev",
            "DB_PASS",
            "secret123",
            &mock,
            "myapp",
            false,
        )
        .await
        .expect("set should succeed");

        let refs = load_refs(dir.path(), "dev").await.unwrap();
        assert_eq!(
            refs.get("DB_PASS").map(String::as_str),
            Some("/myapp/dev/DB_PASS")
        );
    }

    #[tokio::test]
    async fn test_cmd_ssm_set_with_json_output() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_put_param().times(1).returning(|_, _| Ok(()));

        cmd_ssm_set_with(dir.path(), "dev", "API_KEY", "tok", &mock, "myapp", true)
            .await
            .expect("set --json should succeed");
    }

    /// `set` should propagate an error returned by the backend.
    #[tokio::test]
    async fn test_cmd_ssm_set_with_backend_error_propagates() {
        let dir = TempDir::new().unwrap();
        let mut mock = MockSsmBackend::new();
        mock.expect_put_param()
            .times(1)
            .returning(|_, _| Err(GitvaultError::Other("simulated AWS error".to_string())));

        let result = cmd_ssm_set_with(dir.path(), "dev", "KEY", "val", &mock, "myapp", false).await;
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("simulated AWS error")
        );
    }

    // ── cmd_ssm_push_with ─────────────────────────────────────────────────────

    /// Verifies the exact path/value written to SSM for each ref.
    #[tokio::test]
    async fn test_cmd_ssm_push_with_all_vars_set() {
        let dir = TempDir::new().unwrap();
        let mut refs = HashMap::new();
        refs.insert("MY_VAR".to_string(), "/myapp/dev/MY_VAR".to_string());
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        let mut mock = MockSsmBackend::new();
        mock.expect_put_param()
            .withf(|path, value| path == "/myapp/dev/MY_VAR" && value == "hello")
            .times(1)
            .returning(|_, _| Ok(()));

        unsafe { std::env::set_var("MY_VAR", "hello") };
        let result = cmd_ssm_push_with(dir.path(), "dev", &mock, "myapp", false).await;
        unsafe { std::env::remove_var("MY_VAR") };

        result.expect("push should succeed when all env vars are set");
    }

    #[tokio::test]
    async fn test_cmd_ssm_push_with_json_output() {
        let dir = TempDir::new().unwrap();
        let mut refs = HashMap::new();
        refs.insert("PUSH_VAR".to_string(), "/myapp/dev/PUSH_VAR".to_string());
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        let mut mock = MockSsmBackend::new();
        mock.expect_put_param().times(1).returning(|_, _| Ok(()));

        unsafe { std::env::set_var("PUSH_VAR", "value") };
        let result = cmd_ssm_push_with(dir.path(), "dev", &mock, "myapp", true).await;
        unsafe { std::env::remove_var("PUSH_VAR") };

        result.expect("push --json should succeed");
    }

    /// When an env var is absent the command should fail without calling `put_param`.
    #[tokio::test]
    async fn test_cmd_ssm_push_with_missing_env_var_errors() {
        let dir = TempDir::new().unwrap();
        let mut refs = HashMap::new();
        refs.insert(
            "ABSENT_VAR".to_string(),
            "/myapp/dev/ABSENT_VAR".to_string(),
        );
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        // `put_param` must NOT be called — mockall panics if it is.
        let mock = MockSsmBackend::new();
        unsafe { std::env::remove_var("ABSENT_VAR") };

        let result = cmd_ssm_push_with(dir.path(), "dev", &mock, "myapp", false).await;
        assert!(result.is_err(), "push should fail when env var is missing");
    }

    #[tokio::test]
    async fn test_cmd_ssm_push_with_no_refs_errors() {
        let dir = TempDir::new().unwrap();
        // `put_param` must NOT be called.
        let mock = MockSsmBackend::new();

        let result = cmd_ssm_push_with(dir.path(), "dev", &mock, "myapp", false).await;
        assert!(result.is_err(), "push with no refs should fail");
        let msg = result.unwrap_err().to_string();
        assert!(msg.contains("No local SSM references"), "error: {msg}");
    }

    /// Backend error during push propagates correctly.
    #[tokio::test]
    async fn test_cmd_ssm_push_with_backend_error_propagates() {
        let dir = TempDir::new().unwrap();
        let mut refs = HashMap::new();
        refs.insert("VAR".to_string(), "/myapp/dev/VAR".to_string());
        save_refs(dir.path(), "dev", &refs).await.unwrap();

        let mut mock = MockSsmBackend::new();
        mock.expect_put_param()
            .times(1)
            .returning(|_, _| Err(GitvaultError::Other("put failed".to_string())));

        unsafe { std::env::set_var("VAR", "val") };
        let result = cmd_ssm_push_with(dir.path(), "dev", &mock, "myapp", false).await;
        unsafe { std::env::remove_var("VAR") };

        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("put failed"));
    }

    // ── Public command wrappers — error-path coverage ─────────────────────────
    //
    // These tests exercise the public `cmd_ssm_*` functions (which build a
    // `RealSsmBackend` internally) via paths that fail *before* any AWS API
    // call is made, so no live credentials are required.

    /// Helper: create a subdirectory whose name contains characters that are
    /// invalid for an SSM app name (`@`), so that `get_app_name` returns an
    /// error without making any AWS calls.
    fn make_invalid_app_dir(parent: &TempDir) -> std::path::PathBuf {
        let bad = parent.path().join("app@invalid");
        std::fs::create_dir(&bad).expect("create dir");
        bad
    }

    // ── cmd_ssm_pull (public) ─────────────────────────────────────────────────

    /// `cmd_ssm_pull` propagates a `get_app_name` failure that occurs when the
    /// repository directory name contains characters invalid for SSM paths.
    /// No AWS call is made; the error is returned before `build_client`.
    #[tokio::test]
    async fn test_cmd_ssm_pull_invalid_app_name_errors() {
        let parent = TempDir::new().unwrap();
        let bad_dir = make_invalid_app_dir(&parent);
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_pull(&bad_dir, "dev", &aws, false).await;
        assert!(result.is_err(), "should fail for invalid app name");
    }

    /// Same as above but with `json = true` to exercise that branch of the
    /// public wrapper.
    #[tokio::test]
    async fn test_cmd_ssm_pull_json_invalid_app_name_errors() {
        let parent = TempDir::new().unwrap();
        let bad_dir = make_invalid_app_dir(&parent);
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_pull(&bad_dir, "dev", &aws, true).await;
        assert!(result.is_err(), "should fail for invalid app name (json)");
    }

    // ── cmd_ssm_diff (public) ─────────────────────────────────────────────────

    /// `cmd_ssm_diff` propagates a `get_app_name` failure before touching AWS.
    #[tokio::test]
    async fn test_cmd_ssm_diff_invalid_app_name_errors() {
        let parent = TempDir::new().unwrap();
        let bad_dir = make_invalid_app_dir(&parent);
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_diff(&bad_dir, "dev", &aws, false, false).await;
        assert!(result.is_err(), "should fail for invalid app name");
    }

    /// `cmd_ssm_diff` with `reveal = true` still fails at `get_app_name`.
    #[tokio::test]
    async fn test_cmd_ssm_diff_reveal_invalid_app_name_errors() {
        let parent = TempDir::new().unwrap();
        let bad_dir = make_invalid_app_dir(&parent);
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_diff(&bad_dir, "dev", &aws, true, false).await;
        assert!(result.is_err(), "reveal diff should fail for invalid app name");
    }

    // ── cmd_ssm_set (public) ──────────────────────────────────────────────────

    /// `cmd_ssm_set` rejects production writes when `--prod` is absent.
    /// This exercises the public wrapper body up to and including the
    /// `check_prod_barrier` call — no AWS call is needed.
    #[tokio::test]
    async fn test_cmd_ssm_set_prod_barrier_rejects_without_flag() {
        let dir = TempDir::new().unwrap();
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_set(dir.path(), "prod", "KEY", "val", &aws, false, false).await;
        assert!(
            matches!(result, Err(GitvaultError::BarrierNotSatisfied(_))),
            "expected BarrierNotSatisfied, got: {result:?}"
        );
    }

    /// `cmd_ssm_set` propagates `get_app_name` failure (dev env, barrier
    /// passes immediately, then `get_app_name` fails).
    #[tokio::test]
    async fn test_cmd_ssm_set_dev_invalid_app_name_errors() {
        let parent = TempDir::new().unwrap();
        let bad_dir = make_invalid_app_dir(&parent);
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_set(&bad_dir, "dev", "KEY", "val", &aws, false, false).await;
        assert!(result.is_err(), "should fail for invalid app name");
    }

    // ── cmd_ssm_push (public) ─────────────────────────────────────────────────

    /// `cmd_ssm_push` rejects production writes when `--prod` is absent.
    #[tokio::test]
    async fn test_cmd_ssm_push_prod_barrier_rejects_without_flag() {
        let dir = TempDir::new().unwrap();
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_push(dir.path(), "prod", &aws, false, false).await;
        assert!(
            matches!(result, Err(GitvaultError::BarrierNotSatisfied(_))),
            "expected BarrierNotSatisfied, got: {result:?}"
        );
    }

    /// `cmd_ssm_push` propagates `get_app_name` failure (dev env, barrier
    /// passes, then `get_app_name` fails before any AWS call).
    #[tokio::test]
    async fn test_cmd_ssm_push_dev_invalid_app_name_errors() {
        let parent = TempDir::new().unwrap();
        let bad_dir = make_invalid_app_dir(&parent);
        let aws = AwsConfig::from_cli(None, None);
        let result = cmd_ssm_push(&bad_dir, "dev", &aws, false, false).await;
        assert!(result.is_err(), "should fail for invalid app name");
    }
}
